User.destroy_all
u1 = User.create :email => 'jonesy@ga.co', :password => 'chicken', :admin => true
u2 = User.create :email => 'craigsy@ga.co', :password => 'chicken'
puts "#{ User.count } users"

Pokemon.destroy_all
p1 = Pokemon.create :name => 'Bulbasaur', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/bulbasaur.png', :element => 'Grass Poison'
p2 = Pokemon.create :name => 'Ivysaur', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/ivysaur.png', :element => 'Grass Poison'
p3 = Pokemon.create :name => 'Venusaur', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/venusaur.png', :element => 'Grass Poison'
p4 = Pokemon.create :name => 'Charmander', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/charmander.png', :element => 'Fire'
p5 = Pokemon.create :name => 'Charmeleon', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/charmeleon.png', :element => 'Grass Poison'
p6 = Pokemon.create :name => 'Charizard', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/charizard.png', :element => 'Grass Poison'
p7 = Pokemon.create :name => 'Squirtle', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/squirtle.png', :element => 'Grass Poison'
p8 = Pokemon.create :name => 'Wartortle', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/wartortle.png', :element => 'Fire'
p9 = Pokemon.create :name => 'Blastoise', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/blastoise.png', :element => 'Grass Poison'
p10 = Pokemon.create :name => 'Caterpie', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/caterpie.png', :element => 'Grass Poison'
p11 = Pokemon.create :name => 'Metapod', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/metapod.png', :element => 'Grass Poison'
p12 = Pokemon.create :name => 'Butterfree', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/butterfree.png', :element => 'Fire'
p13 = Pokemon.create :name => 'Weedle', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/weedle.png', :element => 'Grass Poison'
p14 = Pokemon.create :name => 'Kakuna', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/kakuna.png', :element => 'Grass Poison'
p15 = Pokemon.create :name => 'Beedrill', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/beedrill.png', :element => 'Grass Poison'
p16 = Pokemon.create :name => 'Pidgey', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/pidgey.png', :element => 'Fire'
p17 = Pokemon.create :name => 'Pidgeotto', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/pidgeotto.png', :element => 'Grass Poison'
p18 = Pokemon.create :name => 'Pidgeot', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/pidgeot.png', :element => 'Grass Poison'
p19 = Pokemon.create :name => 'Rattata', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/rattata.png', :element => 'Grass Poison'
p20 = Pokemon.create :name => 'Raticate', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/raticate.png', :element => 'Fire'
p21 = Pokemon.create :name => 'Spearow', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/spearow.png', :element => 'Grass Poison'
p22 = Pokemon.create :name => 'Fearow', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/fearow.png', :element => 'Grass Poison'
p23 = Pokemon.create :name => 'Ekans', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/ekans.png', :element => 'Grass Poison'
p24 = Pokemon.create :name => 'Arbok', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/arbok.png', :element => 'Fire'
p25 = Pokemon.create :name => 'Pikachu', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/pikachu.png', :element => 'Grass Poison'
p26 = Pokemon.create :name => 'Raichu', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/raichu.png', :element => 'Grass Poison'
p27 = Pokemon.create :name => 'Sandshrew', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/sandshrew.png', :element => 'Grass Poison'
p28 = Pokemon.create :name => 'Sandslash', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/sandslash.png', :element => 'Fire'
p29 = Pokemon.create :name => 'Nidoran♀', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/nidoran-f.png', :element => 'Fire'
p30 = Pokemon.create :name => 'Nidorina', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/nidorina.png', :element => 'Grass Poison'
p31 = Pokemon.create :name => 'Nidoqueen', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/nidoqueen.png', :element => 'Grass Poison'
p32 = Pokemon.create :name => 'Nidoran♂', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/nidoran-m.png', :element => 'Grass Poison'
p33 = Pokemon.create :name => 'Nidorino', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/nidorino.png', :element => 'Fire'
p34 = Pokemon.create :name => 'Nidoking', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/nidoking.png', :element => 'Grass Poison'
p35 = Pokemon.create :name => 'Clefairy', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/clefairy.png', :element => 'Grass Poison'
p36 = Pokemon.create :name => 'Clefable', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/clefable.png', :element => 'Grass Poison'
p37 = Pokemon.create :name => 'Vulpix', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/vulpix.png', :element => 'Fire'
p38 = Pokemon.create :name => 'Ninetales', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/ninetales.png', :element => 'Grass Poison'
p39 = Pokemon.create :name => 'Jigglypuff', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/jigglypuff.png', :element => 'Grass Poison'
p40 = Pokemon.create :name => 'Wigglytuff', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/wigglytuff.png', :element => 'Grass Poison'
p41 = Pokemon.create :name => 'Zubat', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/zubat.png', :element => 'Fire'
p42 = Pokemon.create :name => 'Golbat', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/golbat.png', :element => 'Grass Poison'
p43 = Pokemon.create :name => 'Oddish', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/oddish.png', :element => 'Grass Poison'
p44 = Pokemon.create :name => 'Gloom', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/gloom.png', :element => 'Grass Poison'
p45 = Pokemon.create :name => 'Vileplume', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/vileplume.png', :element => 'Fire'
p46 = Pokemon.create :name => 'Paras', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/paras.png', :element => 'Grass Poison'
p47 = Pokemon.create :name => 'Parasect', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/parasect.png', :element => 'Grass Poison'
p48 = Pokemon.create :name => 'Venonat', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/venonat.png', :element => 'Grass Poison'
p49 = Pokemon.create :name => 'Venomoth', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/venomoth.png', :element => 'Fire'
p50 = Pokemon.create :name => 'Diglett', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/diglett.png', :element => 'Grass Poison'
p51 = Pokemon.create :name => 'Dugtrio', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/dugtrio.png', :element => 'Grass Poison'
p52 = Pokemon.create :name => 'Meowth', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/meowth.png', :element => 'Grass Poison'
p53 = Pokemon.create :name => 'Persian', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/persian.png', :element => 'Fire'
p54 = Pokemon.create :name => 'Psyduck', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/psyduck.png', :element => 'Fire'
p55 = Pokemon.create :name => 'Golduck', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/golduck.png', :element => 'Grass Poison'
p56 = Pokemon.create :name => 'Mankey', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/mankey.png', :element => 'Grass Poison'
p57 = Pokemon.create :name => 'Primeape', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/primeape.png', :element => 'Grass Poison'
p58 = Pokemon.create :name => 'Growlithe', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/growlithe.png', :element => 'Fire'
p59 = Pokemon.create :name => 'Arcanine', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/arcanine.png', :element => 'Grass Poison'
p60 = Pokemon.create :name => 'Poliwag', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/poliwag.png', :element => 'Grass Poison'
p61 = Pokemon.create :name => 'Poliwhirl', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/poliwhirl.png', :element => 'Grass Poison'
p62 = Pokemon.create :name => 'Poliwrath', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/poliwrath.png', :element => 'Fire'
p63 = Pokemon.create :name => 'Abra', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/abra.png', :element => 'Grass Poison'
p64 = Pokemon.create :name => 'Kadabra', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/kadabra.png', :element => 'Grass Poison'
p65 = Pokemon.create :name => 'Alakazam', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/alakazam.png', :element => 'Grass Poison'
p66 = Pokemon.create :name => 'Machop', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/machop.png', :element => 'Fire'
p67 = Pokemon.create :name => 'Machoke', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/machoke.png', :element => 'Grass Poison'
p68 = Pokemon.create :name => 'Machamp', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/machamp.png', :element => 'Grass Poison'
p69 = Pokemon.create :name => 'Bellsprout', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/bellsprout.png', :element => 'Grass Poison'
p70 = Pokemon.create :name => 'Weepinbell', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/weepinbell.png', :element => 'Fire'
p71 = Pokemon.create :name => 'Victreebel', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/victreebel.png', :element => 'Grass Poison'
p72 = Pokemon.create :name => 'Tentacool', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/tentacool.png', :element => 'Grass Poison'
p73 = Pokemon.create :name => 'Tentacruel', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/tentacruel.png', :element => 'Grass Poison'
p74 = Pokemon.create :name => 'Geodude', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/geodude.png', :element => 'Fire'
p75 = Pokemon.create :name => 'Graveler', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/graveler.png', :element => 'Grass Poison'
p76 = Pokemon.create :name => 'Golem', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/golem.png', :element => 'Grass Poison'
p77 = Pokemon.create :name => 'Ponyta', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/ponyta.png', :element => 'Grass Poison'
p78 = Pokemon.create :name => 'Rapidash', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/rapidash.png', :element => 'Fire'
p79 = Pokemon.create :name => 'Slowpoke', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/slowpoke.png', :element => ''
p80 = Pokemon.create :name => 'Slowbro', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/slowbro.png', :element => ''
p81 = Pokemon.create :name => 'Magnemite', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/magnemite.png', :element => ''
p82 = Pokemon.create :name => 'Magneton', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/magneton.png', :element => ''
p83 = Pokemon.create :name => "Farfetch'd", :image => 'https://img.pokemondb.net/sprites/red-blue/normal/farfetchd.png', :element => ''
p84 = Pokemon.create :name => 'Doduo', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/doduo.png', :element => ''
p85 = Pokemon.create :name => 'Dodrio', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/dodrio.png', :element => ''
p86 = Pokemon.create :name => 'Seel', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/seel.png', :element => ''
p87 = Pokemon.create :name => 'Dewgong', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/dewgong.png', :element => ''
p88 = Pokemon.create :name => 'Grimer', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/grimer.png', :element => ''
p89 = Pokemon.create :name => 'Muk', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/muk.png', :element => ''
p90 = Pokemon.create :name => 'Shellder', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/shellder.png', :element => ''
p91 = Pokemon.create :name => 'Cloyster', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/cloyster.png', :element => ''
p92 = Pokemon.create :name => 'Gastly', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/gastly.png', :element => ''
p93 = Pokemon.create :name => 'Haunter', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/haunter.png', :element => ''
p94 = Pokemon.create :name => 'Gengar', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/gengar.png', :element => ''
p95 = Pokemon.create :name => 'Onix', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/onix.png', :element => ''
p96 = Pokemon.create :name => 'Drowzee', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/drowzee.png', :element => ''
p97 = Pokemon.create :name => 'Hypno', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/hypno.png', :element => ''
p98 = Pokemon.create :name => 'Krabby', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/krabby.png', :element => ''
p99 = Pokemon.create :name => 'Kingler', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/kingler.png', :element => ''
p100 = Pokemon.create :name => 'Voltorb', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/voltorb.png', :element => ''
p101 = Pokemon.create :name => 'Electrode', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/electrode.png', :element => ''
p102 = Pokemon.create :name => 'Exeggucute', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/exeggcute.png', :element => ''
p103 = Pokemon.create :name => 'Exeggutor', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/exeggutor.png', :element => ''
p104 = Pokemon.create :name => 'Cubone', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/cubone.png', :element => ''
p105 = Pokemon.create :name => 'Marowak', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/marowak.png', :element => ''
p106 = Pokemon.create :name => 'Hitmonlee', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/hitmonlee.png', :element => ''
p107 = Pokemon.create :name => 'Hitmonchan', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/hitmonchan.png', :element => ''
p108 = Pokemon.create :name => 'Lickitung', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/lickitung.png', :element => ''
p109 = Pokemon.create :name => 'Koffing', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/koffing.png', :element => ''
p110 = Pokemon.create :name => 'Weezing', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/weezing.png', :element => ''
p111 = Pokemon.create :name => 'Rhyhorn', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/rhyhorn.png', :element => ''
p112 = Pokemon.create :name => 'Rhydon', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/rhydon.png', :element => ''
p113 = Pokemon.create :name => 'Chansey', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/chansey.png', :element => ''
p114 = Pokemon.create :name => 'Tangela', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/tangela.png', :element => ''
p115 = Pokemon.create :name => 'Kangaskhan', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/kangaskhan.png', :element => ''
p116 = Pokemon.create :name => 'Horsea', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/horsea.png', :element => ''
p117 = Pokemon.create :name => 'Seadra', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/seadra.png', :element => ''
p118 = Pokemon.create :name => 'Goldeen', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/goldeen.png', :element => ''
p129 = Pokemon.create :name => 'Seaking', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/seaking.png', :element => ''
p120 = Pokemon.create :name => 'Staryu', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/staryu.png', :element => ''
p121 = Pokemon.create :name => 'Starmie', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/starmie.png', :element => ''
p122 = Pokemon.create :name => "Mr.Mime", :image => 'https://img.pokemondb.net/sprites/red-blue/normal/mr-mime.png', :element => ''
p123 = Pokemon.create :name => 'Scyther', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/scyther.png', :element => ''
p124 = Pokemon.create :name => 'Jynx', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/jynx.png', :element => ''
p125 = Pokemon.create :name => 'Electabuzz', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/electabuzz.png', :element => ''
p126 = Pokemon.create :name => 'Magmar', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/magmar.png', :element => ''
p127 = Pokemon.create :name => 'Pinsir', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/pinsir.png', :element => ''
p128 = Pokemon.create :name => 'Tauros', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/tauros.png', :element => ''
p129 = Pokemon.create :name => 'Magikarp', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/magikarp.png', :element => ''
p130 = Pokemon.create :name => 'Gyarados', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/gyarados.png', :element => ''
p131 = Pokemon.create :name => 'Lapras', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/lapras.png', :element => ''
p132 = Pokemon.create :name => 'Ditto', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/ditto.png', :element => ''
p133 = Pokemon.create :name => 'Eevee', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/eevee.png', :element => ''
p134 = Pokemon.create :name => 'Vaporeon', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/vaporeon.png', :element => ''
p135 = Pokemon.create :name => 'Jolteon', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/jolteon.png', :element => ''
p136 = Pokemon.create :name => 'Flareon', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/flareon.png', :element => ''
p137 = Pokemon.create :name => 'Porygon', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/porygon.png', :element => ''
p138 = Pokemon.create :name => 'Omanyte', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/omanyte.png', :element => ''
p139 = Pokemon.create :name => 'Omastar', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/omastar.png', :element => ''
p140 = Pokemon.create :name => 'Kabuto', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/kabuto.png', :element => ''
p141 = Pokemon.create :name => 'Kabutops', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/kabutops.png', :element => ''
p142 = Pokemon.create :name => 'Aerodactyl', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/aerodactyl.png', :element => ''
p143 = Pokemon.create :name => 'Snorlax', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/snorlax.png', :element => ''
p144 = Pokemon.create :name => 'Articuno', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/articuno.png', :element => ''
p145 = Pokemon.create :name => 'Zapdos', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/zapdos.png', :element => ''
p146 = Pokemon.create :name => 'Moltres', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/moltres.png', :element => ''
p147 = Pokemon.create :name => 'Dratini', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/dratini.png', :element => ''
p148 = Pokemon.create :name => 'Dragonair', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/dragonair.png', :element => ''
p149 = Pokemon.create :name => 'Dragonite', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/dragonite.png', :element => ''
p150 = Pokemon.create :name => 'Mewtwo', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/mewtwo.png', :element => ''
p151 = Pokemon.create :name => 'Mew', :image => 'https://img.pokemondb.net/sprites/red-blue/normal/mew.png', :element => ''

puts "#{ Pokemon.count } pokemon"

Move.destroy_all
m1 = Move.create :name => 'Absorb', :category => 'Special'
m2 = Move.create :name => 'Acid', :category => 'Special'
m3 = Move.create :name => 'Acid Armor', :category => 'Status'
m4 = Move.create :name => 'Agility', :category => 'Status'
m5 = Move.create :name => 'Amnesia', :category => 'Status'
m6 = Move.create :name => 'Aurora Beam', :category => 'Special'
m7 = Move.create :name => 'Barrage', :category => 'Physical'
m8 = Move.create :name => 'Barrier', :category => 'Status'
m9 = Move.create :name => 'Bide', :category => 'Physical'
m10 = Move.create :name => 'Bind', :category => 'Physical'
m11 = Move.create :name => 'Bite', :category => 'Physical'
m12 = Move.create :name => 'Blizzard', :category => 'Special'
m13 = Move.create :name => 'Body Slam', :category => 'Physical'
m14 = Move.create :name => 'Bone Club', :category => 'Physical'
m15 = Move.create :name => 'Bonemerang', :category => 'Physical'
m16 = Move.create :name => 'Bubble', :category => 'Special'
m17 = Move.create :name => 'Bubblebeam', :category => 'Special'
m18 = Move.create :name => 'Clamp', :category => 'Physical'
m19 = Move.create :name => 'Comet Punch', :category => 'Physical'
m20 = Move.create :name => 'Confuse Ray', :category => 'Status'
m21 = Move.create :name => 'Confusion', :category => 'Special'
m22 = Move.create :name => 'Constrict', :category => 'Physical'
m23 = Move.create :name => 'Conversion', :category => 'Status'
m24 = Move.create :name => 'Counter', :category => 'Physical'
m25 = Move.create :name => 'Crabhammer', :category => 'Physical'
m26 = Move.create :name => 'Cut', :category => 'Physical'
m27 = Move.create :name => 'Defense Curl', :category => 'Status'
m28 = Move.create :name => 'Dig', :category => 'Physical'
m29 = Move.create :name => 'Disable', :category => 'Status'
m30 = Move.create :name => 'Dizzy Punch', :category => 'Physical'
m31 = Move.create :name => 'Double Kick', :category => 'Physical'
m32 = Move.create :name => 'Double Slap', :category => 'Physical'
m33 = Move.create :name => 'Double Team', :category => 'Status'
m34 = Move.create :name => 'Double-Edge', :category => 'Physical'
m35 = Move.create :name => 'Dragon Rage', :category => 'Special'
m36 = Move.create :name => 'Dream Eater', :category => 'Special'
m37 = Move.create :name => 'Drill Peck', :category => 'Physical'
m38 = Move.create :name => 'Earthquake', :category => 'Physical'
m39 = Move.create :name => 'Egg Bomb', :category => 'Physical'
m40 = Move.create :name => 'Ember', :category => 'Special'
m41 = Move.create :name => 'Explosion', :category => 'Physical'
m42 = Move.create :name => 'Fire Blast', :category => 'Special'
m43 = Move.create :name => 'Fire Punch', :category => 'Physical'
m44 = Move.create :name => 'Fire Spin', :category => 'Special'
m45 = Move.create :name => 'Fissure', :category => 'Physical'
m46 = Move.create :name => 'Flamethrower', :category => 'Special'
m47 = Move.create :name => 'Flash', :category => 'Status'
m48 = Move.create :name => 'Fly', :category => 'Physical'
m49 = Move.create :name => 'Focus Energy', :category => 'Status'
m50 = Move.create :name => 'Fury Attack', :category => 'Physical'
m51 = Move.create :name => 'Fury Swipes', :category => 'Physical'
m52 = Move.create :name => 'Glare', :category => 'Status'
m53 = Move.create :name => 'Growl', :category => 'Status'
m54 = Move.create :name => 'Growth', :category => 'Status'
m55 = Move.create :name => 'Guillotine', :category => 'Physical'
m56 = Move.create :name => 'Gust', :category => 'Special'
m57 = Move.create :name => 'Harden', :category => 'Status'
m58 = Move.create :name => 'Haze', :category => 'Status'
m59 = Move.create :name => 'Headbutt', :category => 'Physical'
m60 = Move.create :name => 'High Jump Kick', :category => 'Physical'
m61 = Move.create :name => 'Horn Attack', :category => 'Physical'
m62 = Move.create :name => 'Horn Drill', :category => 'Physical'
m63 = Move.create :name => 'Hydro Pump', :category => 'Special'
m64 = Move.create :name => 'Hyper Beam', :category => 'Special'
m65 = Move.create :name => 'Hyper Fang', :category => 'Physical'
m66 = Move.create :name => 'Hypnosis', :category => 'Status'
m67 = Move.create :name => 'Ice Beam', :category => 'Special'
m68 = Move.create :name => 'Ice Punch', :category => 'Physical'
m69 = Move.create :name => 'Jump Kick', :category => 'Physical'
m70 = Move.create :name => 'Karate Chop', :category => 'Physical'
m71 = Move.create :name => 'Kinesis', :category => 'Status'
m72 = Move.create :name => 'Leech Life', :category => 'Physical'
m73 = Move.create :name => 'Leech Seed', :category => 'Status'
m74 = Move.create :name => 'Leer', :category => 'Status'
m75 = Move.create :name => 'Lick', :category => 'Physical'
m76 = Move.create :name => 'Light Screen', :category => 'Status'
m77 = Move.create :name => 'Lovely Kiss', :category => 'Status'
m78 = Move.create :name => 'Low Kick', :category => 'Physical'
m79 = Move.create :name => 'Meditate', :category => 'Status'
m80 = Move.create :name => 'Mega Drain', :category => 'Special'
m81 = Move.create :name => 'Mega Kick', :category => 'Physical'
m82 = Move.create :name => 'Mega Punch', :category => 'Physical'
m83 = Move.create :name => 'Metronome', :category => 'Status'
m84 = Move.create :name => 'Mimic', :category => 'Status'
m85 = Move.create :name => 'Minimize', :category => 'Status'
m86 = Move.create :name => 'Mirror Move', :category => 'Status'
m87 = Move.create :name => 'Mist', :category => 'Status'
m88 = Move.create :name => 'Night Shade', :category => 'Special'
m89 = Move.create :name => 'Pay Day', :category => 'Physical'
m90 = Move.create :name => 'Peck', :category => 'Physical'
m91 = Move.create :name => 'Petal Dance', :category => 'Special'
m92 = Move.create :name => 'Pin Missile', :category => 'Physical'
m93 = Move.create :name => 'Poison Gas', :category => 'Status'
m94 = Move.create :name => 'Poison Powder', :category => 'Status'
m95 = Move.create :name => 'Poison Sting', :category => 'Physical'
m96 = Move.create :name => 'Pound', :category => 'Physical'
m97 = Move.create :name => 'Psybeam', :category => 'Special'
m98 = Move.create :name => 'Psychic', :category => 'Special'
m99 = Move.create :name => 'Psywave', :category => 'Special'
m100 = Move.create :name => 'Quick Attack', :category => 'Physical'
m101 = Move.create :name => 'Rage', :category => 'Physical'
m102 = Move.create :name => 'Razor Leaf', :category => 'Physical'
m103 = Move.create :name => 'Razor Wind', :category => 'Special'
m104 = Move.create :name => 'Recover', :category => 'Status'
m105 = Move.create :name => 'Reflect', :category => 'Status'
m106 = Move.create :name => 'Rest', :category => 'Status'
m107 = Move.create :name => 'Roar', :category => 'Status'
m108 = Move.create :name => 'Rock Slide', :category => 'Physical'
m109 = Move.create :name => 'Rock Throw', :category => 'Physical'
m110 = Move.create :name => 'Rolling Kick', :category => 'Physical'
m111 = Move.create :name => 'Sand Attack', :category => 'Status'
m112 = Move.create :name => 'Scratch', :category => 'Physical'
m113 = Move.create :name => 'Screech', :category => 'Status'
m114 = Move.create :name => 'Seismic Toss', :category => 'Physical'
m115 = Move.create :name => 'Self-Destruct', :category => 'Physical'
m116 = Move.create :name => 'Sharpen', :category => 'Status'
m117 = Move.create :name => 'Sing', :category => 'Status'
m118 = Move.create :name => 'Skull Bash', :category => 'Physical'
m119 = Move.create :name => 'Sky Attack', :category => 'Physical'
m120 = Move.create :name => 'Slam', :category => 'Physical'
m121 = Move.create :name => 'Slash', :category => 'Physical'
m122 = Move.create :name => 'Sleep Powder', :category => 'Status'
m123 = Move.create :name => 'Sludge', :category => 'Special'
m124 = Move.create :name => 'Smog', :category => 'Special'
m125 = Move.create :name => 'Smokescreen', :category => 'Status'
m126 = Move.create :name => 'Soft-Boiled', :category => 'Status'
m127 = Move.create :name => 'Solar Beam', :category => 'Special'
m128 = Move.create :name => 'Sonic Boom', :category => 'Special'
m129 = Move.create :name => 'Spike Cannon', :category => 'Physical'
m130 = Move.create :name => 'Splash', :category => 'Status'
m131 = Move.create :name => 'Spore', :category => 'Status'
m132 = Move.create :name => 'Stomp', :category => 'Physical'
m133 = Move.create :name => 'Strength', :category => 'Physical'
m134 = Move.create :name => 'String Shot', :category => 'Status'
m135 = Move.create :name => 'Struggle', :category => 'Physical'
m136 = Move.create :name => 'Stun Spore', :category => 'Status'
m137 = Move.create :name => 'Submission', :category => 'Physical'
m138 = Move.create :name => 'Substitute', :category => 'Status'
m139 = Move.create :name => 'Super Fang', :category => 'Physical'
m140 = Move.create :name => 'Supersonic', :category => 'Status'
m141 = Move.create :name => 'Surf', :category => 'Special'
m142 = Move.create :name => 'Swift', :category => 'Special'
m143 = Move.create :name => 'Swords Dance', :category => 'Status'
m144 = Move.create :name => 'Tackle', :category => 'Physical'
m145 = Move.create :name => 'Tail Whip', :category => 'Status'
m146 = Move.create :name => 'Take Down', :category => 'Physical'
m147 = Move.create :name => 'Teleport', :category => 'Status'
m148 = Move.create :name => 'Thrash', :category => 'Physical'
m149 = Move.create :name => 'Thunder', :category => 'Special'
m150 = Move.create :name => 'Thunder Punch', :category => 'Physical'
m151 = Move.create :name => 'Thunder Shock', :category => 'Special'
m152 = Move.create :name => 'Thunder Wave', :category => 'Status'
m153 = Move.create :name => 'Thunderbolt', :category => 'Special'
m154 = Move.create :name => 'Toxic', :category => 'Status'
m155 = Move.create :name => 'Transform', :category => 'Status'
m156 = Move.create :name => 'Tri Attack', :category => 'Special'
m157 = Move.create :name => 'Twineedle', :category => 'Physical'
m158 = Move.create :name => 'Vine Whip', :category => 'Physical'
m159 = Move.create :name => 'Vise Grip', :category => 'Physical'
m160 = Move.create :name => 'Water Gun', :category => 'Special'
m161 = Move.create :name => 'Waterfall', :category => 'Physical'
m162 = Move.create :name => 'Whirlwind', :category => 'Status'
m163 = Move.create :name => 'Wing Attack', :category => 'Physical'
m164 = Move.create :name => 'Withdraw', :category => 'Status'
m165 = Move.create :name => 'Wrap', :category => 'Physical'
puts "#{ Move.count } moves"

Element.destroy_all
e1 = Element.create :name => 'Fire', :image => 'https://www.shareicon.net/data/128x128/2016/08/01/640199_go_512x512.png'
e2 = Element.create :name => 'Grass', :image => 'https://nexopad.com/static/media/plant-circular.990af6cc.png'
e3 = Element.create :name => 'Water', :image => 'https://icons-for-free.com/iconfiles/png/512/go+pin+pokemon+water+icon-1320186947143161650.png'
e4 = Element.create :name => 'Poison', :image => 'https://www.serebii.net/newpokemonsnap/stickers/typepoison.png'
e5 = Element.create :name => 'Bug', :image => 'http://www.rw-designer.com/icon-image/21178-256x256x32.png'
e6 = Element.create :name => 'Electric', :image => 'https://styles.redditmedia.com/t5_cmx7z/styles/profileIcon_ncr7hj79t8f71.jpg?width=256&height=256&crop=256:256,smart&s=1e3d4e210a461aeb443b2976d1473740fba35db5'
e7 = Element.create :name => 'Fighting', :image => 'https://www.clipartmax.com/png/middle/322-3228840_pokemon-type-symbols-download-pokemon-fighting-type-png.png'
e8 = Element.create :name => 'Rock', :image => 'http://www.rw-designer.com/icon-image/21174-256x256x32.png'
e9 = Element.create :name => 'Ground', :image => 'http://www.rw-designer.com/icon-image/21172-256x256x32.png'
e10 = Element.create :name => 'Ice', :image => 'http://www.rw-designer.com/icon-image/21176-256x256x32.png'
e11 = Element.create :name => 'Flying', :image => 'http://www.rw-designer.com/icon-image/21175-256x256x32.png'
e12 = Element.create :name => 'Normal', :image => 'http://www.rw-designer.com/icon-image/21168-256x256x32.png'
e13 = Element.create :name => 'Psychic', :image => 'http://www.rw-designer.com/icon-image/21185-256x256x32.png'
e14 = Element.create :name => 'Ghost', :image => 'http://www.rw-designer.com/icon-image/21187-256x256x32.png'
e15 = Element.create :name => 'Dragon', :image => 'http://www.rw-designer.com/icon-image/21189-256x256x32.png'
puts "#{ Element.count } types"

# Associations ###################################################
# puts "Pokemon and Elements"
# p6.elements << e1 << e11
# p4.elements << e1
# # Fire
# e1.pokemons << p4 << p5 << p6 << p37 << p38 << p58 << p59 << p77 << p78
# # Grass
# e2.pokemons << p43 << p44 << p45 << p46 << p47 << p69 << p70 << p71 << p102 << p103 << p114

# puts "Pokemon and Moves"
# p1.moves << m1 << m3
# p2.moves << m2

puts "Elements and Moves"
e2.moves << m1
e4.moves << m2 << m3
# m1.element << e2

# puts "Pokemon and Users"
# u1.pokemons << p1 << p2
# u2.pokemons << p2 << p3